StockRequester/StockRequesterWeb/Areas/CompanyAdmin/Controllers/CompanyUsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using StockRequester.DataAccess.Repository.IRepository;
using StockRequester.Models;
using StockRequester.Models.ViewModels;
using StockRequester.Utility;
using StockRequesterWeb.Controllers;

namespace StockRequesterWeb.Areas.CompanyAdmin.Controllers
{
    [Area(nameof(CompanyAdmin))]
    [Authorize(Roles = $"{SD.Role_CompanyAdmin},{SD.Role_SiteAdmin}")]
    public class CompanyUsersController : StockRequesterBaseController
    {
        public CompanyUsersController(IUnitOfWork unitOfWork, UserManager<ApplicationUser> userManager)
            : base(unitOfWork, userManager)
        {
        }

        public IActionResult Index()
        {
            int? companyId = CurrentUserCompanyId();
            if (companyId is null || companyId == 0) return NotFound();

            Company companyFromDb = _unitOfWork.Company.Get(
                u => u.Id == companyId,
                includeProperties: $"{nameof(Company.Users)},{nameof(Company.InvitedEmails)}"
            );

            var allCompanyAdmins = _userManager.GetUsersInRoleAsync(SD.Role_CompanyAdmin).Result;
            var allCompanyUsers  = _userManager.GetUsersInRoleAsync(SD.Role_CompanyUser).Result;

            CompanyUsersViewModel vm = new CompanyUsersViewModel()
            {
                CompanyAdmins = allCompanyAdmins.Where(u => u.CompanyId == companyFromDb.Id),
                CompanyUsers  = allCompanyUsers.Where(u => u.CompanyId == companyFromDb.Id),
                InvitedEmails = companyFromDb.InvitedEmails
            };

            return View(vm);
        }

        public IActionResult Invite()
        {
            InvitedEmail obj = new InvitedEmail()
            {
                CompanyId = CurrentUserCompanyId()
            };

            return View(obj);
        }

        [HttpPost]
        public IActionResult Invite(InvitedEmail obj)
        {
            int? companyId = CurrentUserCompanyId();
            if (companyId is null || companyId == 0) return NotFound();

            Company companyFromDb = _unitOfWork.Company.Get(
                (u => u.Id == companyId),
                includeProperties: nameof(Company.InvitedEmails)
            );

            companyFromDb.InvitedEmails.Add(obj);
            _unitOfWork.Company.Update(companyFromDb);
            _unitOfWork.Save();

            TempData["success"] = $"Created company invite for {obj.Email}";

            return RedirectToAction(nameof(Index));
        }

        public IActionResult DeleteInvite(int id)
        {
            InvitedEmail? invitedEmailFromDb = _unitOfWork.InvitedEmail.Get(u=>u.Id == id);

            if(invitedEmailFromDb is null) return NotFound();

            if(!CurrentUserHasAccess(invitedEmailFromDb)) return NotFound();

            _unitOfWork.InvitedEmail.Remove(invitedEmailFromDb);
            _unitOfWork.Save();

            TempData["success"] = $"Email invite \"{invitedEmailFromDb.Email}\" deleted successfully";

            return RedirectToAction(nameof(Index));
        }
    }
}

StockRequester/StockRequesterWeb/Controllers/CompaniesController.cs
using Microsoft.AspNetCore.Mvc;
using StockRequester.DataAccess.Data;
using StockRequester.DataAccess.Repository.IRepository;
using StockRequester.Models;

namespace StockRequesterWeb.Controllers
{
    public class CompaniesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CompaniesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            List<Company> companiesList = _unitOfWork.Company.GetAll().ToList();
            return View(companiesList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Company obj)
        {
            if(obj.Name is not null &&
              (_unitOfWork.Company.Get(u => u.Name.ToLower() == obj.Name.ToLower()) is not null))
            //(_db.Companies.FirstOrDefault(u => u.Name.ToLower() == obj.Name.ToLower()) is not null))
            {
                ModelState.AddModelError(
                    "name",
                    $"Unfortunately, the company name \"{obj.Name}\"already exists on our system"
                );
            }

            if(!ModelState.IsValid)
            {
                return View();
            }

            _unitOfWork.Company.Add(obj);
            _unitOfWork.Save();
            TempData["success"] = $"Company \"{obj.Name}\" created successfully";
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int? id)
        {
            if(id is null || id == 0)
            {
                return NotFound();
            }

            Company? companyFromDb = _unitOfWork.Company.Get(u=>u.Id == id);
            if(companyFromDb is null)
            {
                return NotFound();
            }

            return View(companyFromDb);
        }

        [HttpPost]
        public IActionResult Edit(Company obj)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            _unitOfWork.Company.Update(obj);
            _unitOfWork.Save();
            TempData["success"] = $"Company \"{obj.Name}\" updated successfully";
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int? id)
        {
            if (id is null || id == 0)
            {
                return NotFound();
            }

            Company? companyFromDb = _unitOfWork.Company.Get(u => u.Id == id);

            if (companyFromDb is null)
            {
                return NotFound();
            }

            return View(companyFromDb);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePOST(int? id)
        {
            if (id is null || id == 0)
            {
                return NotFound();
            }

            Company? companyFromDb = _unitOfWork.Company.Get(u => u.Id == id);

            if (companyFromDb is null)
            {
                return NotFound();
            }

            _unitOfWork.Company.Remove(companyFromDb);
            _unitOfWork.Save();
            TempData["success"] = $"Company \"{companyFromDb.Name}\" deleted successfully";
            return RedirectToAction(nameof(Index));
        }
    }
}

StockRequester/StockRequesterWeb/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Mvc;
using StockRequester.DataAccess.Repository.IRepository;
using StockRequester.Models;

namespace StockRequesterWeb.Controllers
{
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CompanyController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index(int companyId)
        {
            Company obj = _unitOfWork.Company.Get(
                (u=>u.Id == companyId),
                includeProperties: $"{nameof(Company.TransferRequests)}, {nameof(Company.Locations)}"
            );

            return View(obj);
        }
    }
}

StockRequester/StockRequesterWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StockRequester</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StockRequesterWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css"/>
    <style>
        .navbar-dark .navbar-nav .nav-link {
            color: rgba(255, 255, 255, .55);
        }
        .navbar-dark .navbar-nav .nav-link:hover {
            color: rgba(255, 255, 255, .75);
        }
    </style>
</head>
<body>
    <partial name="_CookieConsentPartial" />
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StockRequester</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        @if(User.IsInRole(SD.Role_SiteAdmin))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="SiteAdmin" asp-controller="Companies" asp-action="Index">Companies (Admin View)</a>
                            </li>
                        }
                        @if (User.IsInRole(SD.Role_CompanyUser) || User.IsInRole(SD.Role_CompanyAdmin))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="CompanyUser" asp-controller="Company" asp-action="Index">Company View</a>
                            </li>
                        }
                        @if (User.IsInRole(SD.Role_CompanyAdmin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Company Admin</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item nav-link" asp-area="CompanyAdmin" asp-controller="CompanyUsers" asp-action="Index">Company Users</a>
                                    <a class="dropdown-item nav-link" asp-area="CompanyAdmin" asp-controller="DefaultItemDescription" asp-action="Upsert">Default Item Description</a>
                                    @* <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#">Separated link</a> *@
                                </div>
                            </li>

                            @* <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                              <button type="button" class="btn btn-info">Company Admin</button>
                              <div class="btn-group" role="group">
                                <button id="btnGroupDrop3" type="button" class="btn btn-info dropdown-toggle show" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="true"></button>
                                <div class="dropdown-menu show" aria-labelledby="btnGroupDrop3" style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate3d(0px, 40px, 0px);" data-popper-placement="bottom-start">
                                  <a class="dropdown-item nav-link" asp-area="CompanyAdmin" asp-controller="CompanyUsers" asp-action="Index">Company Users</a>
                                  <a class="dropdown-item nav-link" asp-area="CompanyAdmin" asp-controller="DefaultItemDescription" asp-action="Upsert">Default Item Description</a>
                                </div>
                              </div>
                            </div>

                            <li class="nav-item">
                                <a class="nav-link" asp-area="CompanyAdmin" asp-controller="CompanyUsers" asp-action="Index">Company Users</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-area="CompanyAdmin" asp-controller="DefaultItemDescription" asp-action="Upsert">Default Item Description</a>
                            </li> *@
                        }
                    </ul>

                    <partial name="_LoginPartial" />

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-dark text-muted">
        <div class="container">
            &copy; 2025 StockRequester. All rights reserved.
            -
            <a asp-area="" asp-controller="Home" asp-action="About">About</a>
            -
            <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

StockRequester/StockRequesterWeb/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">

        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-bottom-left",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }

        toastr.success('@TempData["success"]');
        
    </script>
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">

        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-bottom-left",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }

        toastr.error('@TempData["error"]');
    </script>
}