StockRequester/StockRequesterWeb/Areas/CompanyUser/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using StockRequester.DataAccess.Repository.IRepository;
using StockRequester.Models;
using StockRequester.Models.ViewModels;
using StockRequester.Utility;
using StockRequesterWeb.Areas.SiteAdmin.Controllers;
using StockRequesterWeb.Controllers;

namespace StockRequesterWeb.Areas.CompanyUser.Controllers
{
    [Area(nameof(CompanyUser))]
    [Authorize]
    public class CompanyController : StockRequesterBaseController
    {
        public CompanyController(IUnitOfWork unitOfWork, UserManager<ApplicationUser> userManager)
            : base(unitOfWork, userManager)
        {
        }

        public IActionResult Index()
        {
            int? companyId = CurrentUserCompanyId();
            if (companyId is null || companyId == 0)
            {
                if (User.IsInRole(SD.Role_CompanyAdmin))
                {
                    return RedirectToAction(nameof(RegisterCompany));
                }
                else if (User.IsInRole(SD.Role_CompanyUser))
                {
                    return RedirectToAction(nameof(JoinCompany));
                }
            }

            Company companyFromDb = _unitOfWork.Company.Get(
                u => u.Id == companyId,
                includeProperties: $"{nameof(Company.TransferRequests)},{nameof(Company.Locations)},{nameof(Company.Users)}"
            );

            foreach (TransferRequest tr in companyFromDb.TransferRequests)
            {
                tr.Status = _unitOfWork.RequestStatus.Get(u => u.Id == tr.StatusId);
            }

            return View(companyFromDb);
        }

        [Authorize(Roles = SD.Role_CompanyAdmin)]
        public IActionResult RegisterCompany()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = SD.Role_CompanyAdmin)]
        public IActionResult RegisterCompany(Company obj)
        {
            //if (obj.Name is not null &&
            //  _unitOfWork.Company.Get(u => u.Name.ToLower() == obj.Name.ToLower()) is not null)
            //{
            //    ModelState.AddModelError(
            //        "name",
            //        $"Unfortunately, the company name \"{obj.Name}\"already exists on our system"
            //    );
            //}

            if (!ModelState.IsValid)
            {
                return View();
            }

            _unitOfWork.Company.Add(obj);
            _unitOfWork.Save();

            ApplicationUser? applicationUser = CurrentApplicationUser();

            if (applicationUser is null)
            {
                return NotFound();
            }

            if(obj.Id != 0)
            {
                applicationUser.CompanyId = obj.Id;
                _unitOfWork.ApplicationUser.Update(applicationUser);
                _unitOfWork.Save();
            }
            else
            {
                TempData["error"] = $"Company ID was not saved to this user's data";
            }

            TempData["success"] = $"Company \"{obj.Name}\" created successfully";
            return RedirectToAction(nameof(Index));

        }

        [Authorize(Roles = SD.Role_CompanyUser)]
        public IActionResult JoinCompany()
        {
            ApplicationUser? applicationUser = CurrentApplicationUser();
            if(applicationUser is null)
            {
                return NotFound();
            }

            InvitedEmail? invitedEmailFromDb = _unitOfWork.InvitedEmail.Get(
                (u=>u.Email == applicationUser.Email),
                includeProperties: nameof(InvitedEmail.Company)
            );

            if (invitedEmailFromDb is not null)
            {
                return View(invitedEmailFromDb);
            }
            else
            {
                return View("NoInvite", applicationUser.Email);
            }
            
        }

        [HttpPost]
        [Authorize(Roles = SD.Role_CompanyUser)]
        public IActionResult JoinCompany(InvitedEmail invitedEmail)
        {
            if (!ModelState.IsValid)
            {
                return NotFound();
            }

            ApplicationUser? applicationUser = CurrentApplicationUser();

            if (applicationUser is null)
            {
                return NotFound();
            }

            if (invitedEmail.CompanyId != 0)
            {
                applicationUser.CompanyId = invitedEmail.CompanyId;
                _unitOfWork.ApplicationUser.Update(applicationUser);
                InvitedEmail invitedEmailFromDb = _unitOfWork.InvitedEmail.Get(u=>u.Id == invitedEmail.Id);
                _unitOfWork.InvitedEmail.Remove(invitedEmailFromDb);
                _unitOfWork.Save();
                TempData["success"] = $"Joined company successfully";
            }
            else
            {
                TempData["error"] = $"Company ID was not saved to this user's data";
            }

            return RedirectToAction(nameof(Index));
        }

        public IActionResult ArchivedIndex()
        {
            int? companyId = CurrentUserCompanyId();

            if (companyId is null || companyId == 0)
            {
                return RedirectToAction(nameof(Index));
            }

            Company companyFromDb = _unitOfWork.Company.Get(
                u => u.Id == companyId,
                includeProperties: $"{nameof(Company.TransferRequests)},{nameof(Company.Locations)},{nameof(Company.Users)}"
            );

            foreach (TransferRequest tr in companyFromDb.TransferRequests)
            {
                tr.Status = _unitOfWork.RequestStatus.Get(u => u.Id == tr.StatusId);
            }

            return View(companyFromDb);
        }
    }
}

StockRequester/StockRequesterWeb/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Mvc;
using StockRequester.DataAccess.Repository.IRepository;
using StockRequester.Models;

namespace StockRequesterWeb.Controllers
{
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CompanyController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index(int companyId)
        {
            Company obj = _unitOfWork.Company.Get(
                (u=>u.Id == companyId),
                includeProperties: $"{nameof(Company.TransferRequests)}, {nameof(Company.Locations)}"
            );

            return View(obj);
        }
    }
}

StockRequester/StockRequesterWeb/Controllers/LocationController.cs
using Microsoft.AspNetCore.Mvc;
using StockRequester.DataAccess.Repository.IRepository;
using StockRequester.Models;
using StockRequester.Utility;

namespace StockRequesterWeb.Controllers
{
    public class LocationController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public LocationController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index(int id)
        {
            Location? locationFromDb = _unitOfWork.Location.Get(
                (u => u.Id == id),
                includeProperties: $"{nameof(Location.TransferRequestsFromThisOrigin)},{nameof(Location.TransferRequestsToThisDestination)}"
            );

            if (locationFromDb is null)
            {
                return NotFound();
            }

            foreach(TransferRequest tc in locationFromDb.TransferRequestsFromThisOrigin)
            {
                tc.OriginLocation      = _unitOfWork.Location.Get(u => u.Id == tc.OriginLocationId);
                tc.DestinationLocation = _unitOfWork.Location.Get(u => u.Id == tc.DestinationLocationId);
            }

            foreach (TransferRequest tc in locationFromDb.TransferRequestsToThisDestination)
            {
                tc.OriginLocation = _unitOfWork.Location.Get(u => u.Id == tc.OriginLocationId);
                tc.DestinationLocation = _unitOfWork.Location.Get(u => u.Id == tc.DestinationLocationId);
            }

            return View(locationFromDb);
        }

        public IActionResult Upsert(int companyId, int? id)
        {
            if(companyId == 0)
            {
                string errorMessage = "No company ID for Upsert action";
                ModelState.AddModelError(
                    "",
                    errorMessage
                );
                TempData["error"] = errorMessage;
            }

            if(!ModelState.IsValid)
            {
                return View();
            }

            Location location;
            bool locationAlreadyExists = !(id is null || id == 0);
            if(locationAlreadyExists) // update
            {
                location = _unitOfWork.Location.Get(
                    (u => u.Id == id),
                    includeProperties: nameof(Location.Company)
                );
            }
            else // insert
            {
                location = new Location();
                location.CompanyId = companyId;

                Company companyFromDb = _unitOfWork.Company.Get(u => u.Id == companyId);
                location.Company = companyFromDb;

            }
            
            return View(location);
        }

        [HttpPost]
        public IActionResult Upsert(Location obj)
        {
            Company company = _unitOfWork.Company.Get(
                (u => u.Id == obj.CompanyId),
                includeProperties: nameof(Company.Locations)
            );
            

            Location? anyOtherWithSameName = company.Locations.ToList().Find(location => location.Name.ToLower() == obj.Name.ToLower());
            if (
              obj.Name is not null &&
              anyOtherWithSameName is not null &&
              anyOtherWithSameName.Id != obj.Id
            )
            {
                ModelState.AddModelError(
                    "name",
                    $"Your company already has a location named \"{obj.Name}\""
                );
            }

            if (!ModelState.IsValid)
            {
                TempData["error"] = $"ModelState is not valid";
                return View(obj);
            }

            bool locationAlreadyExists = !(obj.Id == 0);

            if(locationAlreadyExists)
            {
                _unitOfWork.Location.Update(obj);
            }
            else
            {
                _unitOfWork.Location.Add(obj);
            }
            _unitOfWork.Save();
            TempData["success"] = $"Location \"{obj.Name}\" {(locationAlreadyExists ? "updated" : "created")} successfully";

            return RedirectToAction(nameof(Index), ControllerUtility.ControllerName(typeof(CompanyController)), new { companyId = obj.CompanyId } );
        }

        public IActionResult Delete(int? id)
        {
            if (id is null || id == 0)
            {
                return NotFound();
            }

            Location? locationFromDb = _unitOfWork.Location.Get(
                (u => u.Id == id),
                includeProperties: $"{nameof(Location.TransferRequestsFromThisOrigin)},{nameof(Location.TransferRequestsToThisDestination)}"
            );

            if (locationFromDb is null)
            {
                return NotFound();
            }

            return View(locationFromDb);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePOST(int? id)
        {
            if (id is null || id == 0)
            {
                return NotFound();
            }

            Location? locationFromDb = _unitOfWork.Location.Get(u => u.Id == id);

            if (locationFromDb is null)
            {
                return NotFound();
            }

            int companyId = locationFromDb.CompanyId;
            
            _unitOfWork.Location.Remove(locationFromDb);
            _unitOfWork.Save();
            TempData["success"] = $"Location \"{locationFromDb.Name}\" deleted successfully";

            return RedirectToAction(nameof(Index), ControllerUtility.ControllerName(typeof(CompanyController)), new { companyId = companyId });
        }

    }
}

StockRequester/StockRequesterWeb/Controllers/TransferRequestController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using StockRequester.DataAccess.Repository.IRepository;
using StockRequester.Models;
using StockRequester.Models.ViewModels;
using StockRequester.Utility;
using System.Transactions;

namespace StockRequesterWeb.Controllers
{
    public class TransferRequestController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public TransferRequestController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Upsert(int companyId, int? id, int? originLocationId, int? destinationLocationId, int? backLocationId)
        {
            if (companyId == 0)
            {
                string errorMessage = "No company ID for Upsert action";
                ModelState.AddModelError(
                    "",
                    errorMessage
                );
                TempData["error"] = errorMessage;
            }

            if (!ModelState.IsValid)
            {
                return View();
            }

            Company companyFromDb = _unitOfWork.Company.Get(
                (u => u.Id == companyId),
                includeProperties: nameof(Company.Locations)
            );

            TransferRequest tr;
            bool locationAlreadyExists = !(id is null || id == 0);
            if (locationAlreadyExists) // update
            {
                tr = _unitOfWork.TransferRequest.Get(
                    (u => u.Id == id),
                    includeProperties: $"{nameof(TransferRequest.Company)},{nameof(TransferRequest.OriginLocation)},{nameof(TransferRequest.DestinationLocation)}"
                );
            }
            else // insert
            {
                tr = new TransferRequest();
                tr.CompanyId = companyId;

                tr.Company = companyFromDb;
            }

            if(originLocationId is not null && originLocationId != 0)
            {
                tr.OriginLocationId = originLocationId;
            }

            if(destinationLocationId is not null && destinationLocationId != 0)
            {
                tr.DestinationLocationId = destinationLocationId;
            }

            IEnumerable<SelectListItem> companyLocationsList = companyFromDb.Locations.Select(
                u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }
            );

            TransferRequestViewModel trVm = new()
            {
                TransferRequest = tr,
                CompanyLocationsList = companyLocationsList,
                BackLocation = backLocationId is not null ? _unitOfWork.Location.Get(u=>u.Id==backLocationId) : null
            };

            return View(trVm);
        }

        [HttpPost]
        public IActionResult Upsert(TransferRequestViewModel trVm)
        {
            TransferRequest obj = trVm.TransferRequest;

            Company companyFromDb = _unitOfWork.Company.Get(
                (u => u.Id == obj.CompanyId),
                includeProperties: nameof(Company.Locations)
            );

            if (!ModelState.IsValid)
            {
                TempData["error"] = $"ModelState is not valid";

                trVm.CompanyLocationsList = companyFromDb.Locations.Select(
                    u => new SelectListItem
                    {
                        Text = u.Name,
                        Value = u.Id.ToString()
                    }
                );

                return View(trVm);
            }

            bool trAlreadyExists = !(obj.Id == 0);

            if (trAlreadyExists)
            {
                _unitOfWork.TransferRequest.Update(obj);
            }
            else
            {
                _unitOfWork.TransferRequest.Add(obj);
            }
            _unitOfWork.Save();
            TempData["success"] = $"Transfer request {(trAlreadyExists ? "updated" : "created")} successfully";

            return RedirectToAction(nameof(Index), ControllerUtility.ControllerName(typeof(CompanyController)), new { companyId = obj.CompanyId });
        }


        public IActionResult Delete(int? id)
        {
            if (id is null || id == 0)
            {
                return NotFound();
            }

            TransferRequest? trFromDb = _unitOfWork.TransferRequest.Get(
                (u => u.Id == id),
                includeProperties: $"{nameof(TransferRequest.DestinationLocation)},{nameof(TransferRequest.OriginLocation)}"
            );

            if (trFromDb is null)
            {
                return NotFound();
            }

            return View(trFromDb);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePOST(int? id)
        {
            if (id is null || id == 0)
            {
                return NotFound();
            }

            TransferRequest? trFromDb = _unitOfWork.TransferRequest.Get(u => u.Id == id);

            if (trFromDb is null)
            {
                return NotFound();
            }

            int companyId = trFromDb.CompanyId;

            _unitOfWork.TransferRequest.Remove(trFromDb);
            _unitOfWork.Save();
            TempData["success"] = $"Transfer Request deleted successfully";

            return RedirectToAction(nameof(Index), ControllerUtility.ControllerName(typeof(CompanyController)), new { companyId = companyId });
        }
    }
}

StockRequester/StockRequesterWeb/Areas/CompanyUser/Views/Company/ArchivedIndex.cshtml
@model Company

@{
    ViewData["Title"] = $"Archived Requests - {Model.Name}";
}

<div class="container">
    <div class="row pt-4">
        <div class="col-6">
            <h1 class="text-primary">
                Archived Requests - @Model.Name
            </h1>
        </div>
        <div class="col-6 text-end">
        </div>
    </div>
</div>

<hr />

@await Html.PartialAsync(
        "../TransferRequest/_TransferRequestsTable.cshtml",
        new TrTableViewModel
    {
        TransferRequests = Model.TransferRequests,
        TableOptions = TrTableOptions.ForArchivedView()
    }
    )

<hr />

<a asp-controller="Company" asp-action="Index" class="btn btn-secondary mx-2">
    <i class="bi bi-arrow-left-circle"></i> Back to Company View
</a>

StockRequester/StockRequesterWeb/Areas/CompanyUser/Views/Company/Index.cshtml
@model Company

@{
    ViewData["Title"] = Model.Name;
}

<div class="container">
    <div class="row pt-4">
        <div class="col-6">
            <h1 class="text-primary">
                @Model.Name
            </h1>
        </div>
        <div class="col-6 text-end">
        </div>
    </div>
</div>

<hr />


<div class="container">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">
                <i class="bi bi-pin-map"></i> Locations
            </h2>
        </div>
        <div class="col-6 text-end">
            @if(User.IsInRole(SD.Role_CompanyAdmin))
            {
                <a asp-controller="Location" asp-action="Upsert" class="btn btn-primary">
                    <i class="bi bi-plus-circle"></i> Create A New Location
                </a>
            }
        </div>
    </div>
</div>

<hr/>

<table class="table table-bordered border-white table-striped">
    <thead>
        <tr>
            <th class="text-white">
                <b>Location Name</b>
            </th>
            <th class="text-white">
                <b>Actions</b>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var obj in Model.Locations.OrderBy(u => u.Name))
        {
            <tr>
                <td class="text-white">
                    @obj.Name
                </td>
                <td>
                    <div class="w-100 btn-group" role="group">

                        <a asp-controller="Location" asp-action="Index" asp-route-id="@obj.Id" class="btn btn-info mx-2">
                            <i class="bi bi-card-list"></i> Go To Location View
                        </a>

                        @if (User.IsInRole(SD.Role_CompanyAdmin))
                        {
                            <a asp-controller="Location" asp-action="Upsert" asp-route-id="@obj.Id" class="btn btn-primary mx-2">
                                <i class="bi bi-pencil"></i> Rename
                            </a>

                            <a asp-controller="Location" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger mx-2">
                                <i class="bi bi-trash3"></i> Delete
                            </a>
                        }
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

<hr />



<div class="container">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">
                <i class="bi bi-truck"></i> All Transfer Requests
            </h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="TransferRequest" asp-action="Upsert" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> Create A New Transfer Request
            </a>
        </div>
    </div>
</div>

<hr />

@await Html.PartialAsync(
    "../TransferRequest/_TransferRequestsTable.cshtml", 
    new TrTableViewModel{
        TransferRequests = Model.TransferRequests,
        TableOptions = TrTableOptions.ForCompanyView()
    }
)

<div class="row mt-3">
    <div class="col-6 col-md-9">
    </div>
    <div class="col-6 col-md-3 text-end">
        <a asp-controller="Company" asp-action="ArchivedIndex" class="btn btn-secondary border form-control">
            <i class="bi bi-archive"></i> View Archived Requests
        </a>
    </div>
    <div class="col-6 col-md-3">
    </div>
</div>

<hr/>

<div class="container">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">
                <i class="bi bi-person"></i> Users
            </h2>
        </div>
        <div class="col-6 text-end">
            
        </div>
    </div>
</div>

<hr />

<table class="table table-bordered border-white table-striped">
    <thead>
        <tr>
            <th class="text-white">
                <b>Name</b>
            </th>
            <th class="text-white">
                <b>Email Address</b>
            </th>
            <th class="text-white">
                <b>Actions</b>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var obj in Model.Users.OrderBy(u => u.Name))
        {
            <tr>
                <td class="text-white">
                    @obj.Name
                </td>
                <td class="text-white">
                    @obj.Email
                </td>

                <td class="text-white">
                    <div class="w-100 btn-group" role="group">
                        @* <a asp-controller="TransferRequest" asp-action="Upsert" asp-route-companyId="@Model.Id" asp-route-id="@obj.Id" class="btn btn-primary mx-2">
                            <i class="bi bi-pencil"></i> Edit
                        </a>

                        <a asp-controller="TransferRequest" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger mx-2">
                            <i class="bi bi-trash3"></i> Delete
                        </a> *@
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>


<hr />

StockRequester/StockRequesterWeb/Areas/CompanyUser/Views/Company/JoinCompany.cshtml
@{
    ViewData["Title"] = "Join Company";
}

@model InvitedEmail

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Join Company</h2>
            <hr />
        </div>

        <p>@Model.Company.Name</p>
        <input asp-for="Id" hidden />
        <input asp-for="Email" hidden />
        <input asp-for="CompanyId" hidden />
        <input asp-for="Company" hidden />
        <div class="row p-1">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-primary">
                    <i class="bi bi-check-circle"></i> Join Company
                </button>
            </div>
            <div class="col-6 col-md-3">
            </div>
        </div>

    </div>
</form>

StockRequester/StockRequesterWeb/Areas/CompanyUser/Views/Company/NoInvite.cshtml
@{
    ViewData["Title"] = "No Invite";
}

@model string //user's email address

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">No Invite Found</h2>
            <hr />
        </div>
        <div class="mb-3 row p-1">
            <p>
                @Model has not been invited to join a company yet<br />
                Ask your company admin to get invited
            </p>
        </div>

    </div>
</form>

StockRequester/StockRequesterWeb/Areas/CompanyUser/Views/Company/RegisterCompany.cshtml
@{
    ViewData["Title"] = "Register Company";
}

@model Company

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Register Company</h2>
            <hr />
        </div>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="mb-3 row p-1">
            <label asp-for="Name" class="p-0"></label>
            <input asp-for="Name" type="text" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div class="row p-1">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-primary">
                    <i class="bi bi-check-circle"></i> Register Company
                </button>
            </div>
            <div class="col-6 col-md-3">
            </div>
        </div>

    </div>
</form>


@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}